# Site settings
title: GetHosp
email: fushenghua2012@gmail.com
description: "GetHosp 数据源自网络，不代表我们的任何观点。"
baseurl: "http://fushenghua.github.io/GetHosp"
# twitter_username: GetHosp
github_username:  fushenghua
url: "http://fushenghua.github.io/GetHosp"

# Build settings
markdown: kramdown
permalink: pretty

include: [.html]
paginator: true
