# Site settings
title: GetHosp
email: fushenghua@2012.com
description: "GetHosp"
baseurl: ""
url: "http://GetHosp.com"
twitter_username: GetHosp
github_username:  GetHosp

# Build settings
markdown: kramdown
permalink: pretty
